### PR TITLE
add a basic CLI

### PR DESCRIPTION
**Pull request by zeke**
This is a primitive CLI but it works for my purposes. If you're interested in merging this I can spruce it up by adding tests and supporting command line options for `size`, `default` and whatnot. But if you're not interested I won't bother. Thanks!

### CODE REVIEW

**Comment by emerleite** [comment]
Looks Good, @zeke. Could you rebase your branch to be up to date and add some tests?

**Comment by zeke** [comment]
@emerleite rebased and added tests!

Sorry about the full rewrite of package.json -- the npm client does that automatically.

**Comment by zeke** [comment]
The CI is failing on Node 0.8. That's a pretty old version of node.. do you want to keep supporting it?

**Comment by emerleite** [comment]
Surely not :)

**Comment by emerleite** [comment]
Merged. It will be nice if you continue with this. Are you interested @zeke ?

**Comment by emerleite** [comment]
@zeke released 1.4.0. Thanks !!!

**Comment by zeke** [comment]
:metal:

**Pull request merged**
